### ISSUE TITLE
Zone type analysis: Need numbers for percentage of routes that are residential in the density based zone types (section 4.5.2)

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/sidewalk-data-analysis#20]
This is for the statement in the paper that talks about the results from the density-based zone type analysis: Within the density-based zone types, there is a high percentage of routes that are residential in both groups. For more context, refer to section 4.5.2.

**Comment by misaugstad** [comment]
Of the 43 low-moderate density routes, 41 were residential (95.35%). And of the 23 medium-high density routes, 13 were residential (56.52%).

I am also adding these numbers to the stats_for_paper.md doc in the density based zone type section.
