### ISSUE TITLE
Table: Updating table showing accuracy and behavioral statistics for user groups (section 4.6)

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/sidewalk-data-analysis#29]
Current table shows median accuracy measures and behavioral metrics:
![image](https://user-images.githubusercontent.com/2873216/40274477-f0be238e-5b8b-11e8-9571-8d4ff0dd2f86.png)

by user groups:
![image](https://user-images.githubusercontent.com/2873216/40274479-f824f92c-5b8b-11e8-81cb-add130e2d482.png)

We need to update the table to add:
1. Visual Search time for different groups
2. SDs for accuracy numbers

**Comment by manaswis** [comment]
Updated table with the added values would look something like this:

![image](https://user-images.githubusercontent.com/2873216/40569893-6121b426-603a-11e8-8561-7a9c95f6600f.png)

**Comment by jonfroehlich** [comment]
Please make it so that SD is to the right of the main number in each cell rather than below it. If it's below, you cannot vertically scan the numbers. Use a horizontally condensed font like Segoe Condensed or Arial Narrow as necessary.

**Comment by manaswis** [comment]
Okay, I will change the font. It is currently on the right of the main
number. However, it doesn’t fit in the space.

**Comment by manaswis** [comment]
> Also, should recall go first?

The usual convention is to put precision first. But we can go with recall first since that is the most important metric for us.

> And while I like your cell highlighting, perhaps you need to highlight all cells (e.g., using a gradient based on cell number value) rather than just specific cells.

I was using two color highlights: green (>80% accuracy) and red (<40% accuracy) to draw attention. Should I make a mono-color gradient? 

> Why are we using median rather than average?

We use median throughout the paper for the first number and then mention mean and SD in the parenthesis. That's what we selected because it was a better metric than mean when the data is skewed towards either sides.

> Finally, is there a reason why we are splitting up All and Problem? Do you think this is important? Are we consistently doing this throughout the paper? 

"All" is across all label types and "problem" is for identifying a problem type. We have been using both throughout the paper. We have been using "all" to report overall accuracy across all label types, and have been using "problem" similar to CHI13.

> Does the value of doing this split outweigh the additional challenge of presenting the data?

I think reporting both is important in the label type vs accuracy section. However, in this section where we are comparing between user groups, we can just talk about their accuracy across all label types and drop "problem" type. Thoughts?

**Comment by misaugstad** [comment]
>Finally, is there a reason why we are splitting up All and Problem? Do you think this is important? Are we consistently doing this throughout the paper?

I do think it is important to make the distinction. Curb ramp accuracy is very high across the board, and the large number of curb ramps end up causing curb ramp data to sort of crowd out the other data. This is a problem because, although identifying accessibility features _is_ important, the really important thing we are trying to do is identify accessibility _problems_. So I do think it is worth showing both in most cases.
