### ISSUE TITLE
Details for Turk Deployment Period needed

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/sidewalk-data-analysis#38]
We used the volunteer data from September 2016 - August 2017 for our turk study. What was DC's completion rate at that time and how many labels were contributed?

**Comment by misaugstad** [comment]
Just did the calculation. DC was 51.96% complete. There were 169,653 labels (162,881 if you exclude tutorial labels). You can close this issue once you've moved those numbers into the paper.

**Comment by manaswis** [comment]
Thanks Mikey!
